### ISSUE TITLE
Camera System Enhancement

### ISSUE THREAD

**Issue by Exocizcs** [Exocizcs/PixelFarm#7]
### Camera Movement and Follow with Boundaries
**Camera Movement Jittery**
- When camera moving not smooth and creates jittery movement

**Boundary Implementation**
- Camera Boundary to limit camera movement and force scene ration when changing from one device to another

**Comment by annieooijiayi** [comment]
To approach this issue, we have discussed and decided to make a camera system script instead of Cinematic. Most beginners choose Cinematic as it is relatively easy but we don't recommend it for 2D as typed script will be working better and perform well
