### ISSUE TITLE
Enemy following Script

### ISSUE THREAD

**Issue by Exocizcs** [Exocizcs/PixelFarm#8]
### Enemy auto follow script
**Required Enemy AI Script**
- Implementation of Minotaur as enemy to chase after player in certain range

**Comment by Exocizcs** [comment]
Enemy System is expected to implement for next step

**Comment by choonhongyeoh0241** [comment]
This system is expected to take some times as it is relatively new and hard at the same time as Simple Enemy AI is expected at the same time

**Comment by Exocizcs** [comment]
Animation will be done on my end, thank you for the script
